# TODO ADD YOUR CODE HERE 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: # ENTER STWP 1
      uses: # ENTER COMMAND 1

    - name: 
      uses: # ENTER USE CASE 1
      with:
        python-version: '3.8'

    - name: 
      run: |
        pip install -r requirements.txt
